namespace ReCap.Parser.Catalog;

public sealed class LootPreferences : AssetCatalog
{
    protected override void Build()
    {
        Struct("LootPreferences", 0x4bc, // 0x43 entries
            Field("slotChance_Offense", DataType.Float, 0x0),
            Field("slotChance_Defense", DataType.Float, 0x4),
            Field("slotChance_Utility", DataType.Float, 0x8),
            Field("slotChance_Weapon", DataType.Float, 0xc),
            Field("slotChance_Foot", DataType.Float, 0x10),
            Field("slotChance_Hand", DataType.Float, 0x14),
            Field("scienceChance_Tech", DataType.Float, 0x18),
            Field("scienceChance_Quantum", DataType.Float, 0x1c),
            Field("scienceChance_Bio", DataType.Float, 0x20),
            Field("scienceChance_Plasma", DataType.Float, 0x24),
            Field("scienceChance_Necro", DataType.Float, 0x28),
            Field("npcDropRarityChances_Basic", DataType.Char, 0x2c, 0x80),
            Field("npcDropRarityChances_Uncommon", DataType.Char, 0xac, 0x80),
            Field("npcDropRarityChances_Rare", DataType.Char, 0x12c, 0x80),
            Field("npcDropRarityChances_Epic", DataType.Char, 0x1ac, 0x80),
            Field("majorLevelMultiplier", DataType.Int, 0x22c),
            Field("minorLevelMultiplier", DataType.Int, 0x230),
            Field("lastMinorLevelBonus", DataType.Int, 0x234),
            Field("rarityLevelMultiplier", DataType.Int, 0x238),
            Field("pointValue_BasePoints", DataType.Float, 0x22c),
            Field("pointValue_ExponentBasesPerItemLevel", DataType.Char, 0x240, 0x80),
            Field("pointValue_ExtraStatsBonusFactor", DataType.Float, 0x2c0),
            Field("pointCost_Strength", DataType.Int, 0x2c4),
            Field("pointCost_Dexterity", DataType.Int, 0x2c8),
            Field("pointCost_Mind", DataType.Int, 0x2cc),
            Field("pointCost_Health", DataType.Int, 0x2d0),
            Field("pointCost_Mana", DataType.Int, 0x2d4),
            Field("pointCost_Critical", DataType.Int, 0x2d8),
            Field("pointCost_Dodge", DataType.Int, 0x2dc),
            Field("pointCost_Deflection", DataType.Int, 0x2e0),
            Field("pointCost_PhysicalDamageDecreaseFlat", DataType.Int, 0x2e4),
            Field("pointCost_EnergyDamageDecreaseFlat", DataType.Int, 0x2e8),
            Field("pointCost_MinWeaponDamage", DataType.Int, 0x2ec),
            Field("pointCost_MaxWeaponDamage", DataType.Int, 0x2f0),
            Field("pointCost_DirectAttackDamage", DataType.Int, 0x2f4),
            Field("basic_StandardDist", DataType.Float, 0x2f8),
            Field("basic_SuffixDist", DataType.Float, 0x2fc),
            Field("uncommon_SuffixDist", DataType.Float, 0x300),
            Field("uncommon_Prefix1Dist", DataType.Float, 0x304),
            Field("uncommon_Prefix2Dist", DataType.Float, 0x2dc),
            Field("uncommon_StandardDist", DataType.Float, 0x30c),
            Field("rare_SuffixDist", DataType.Float, 0x310),
            Field("rare_Prefix1Dist", DataType.Float, 0x314),
            Field("rare_Prefix2Dist", DataType.Float, 0x318),
            Field("rare_StandardDist", DataType.Float, 0x31c),
            Field("epic_SuffixDist", DataType.Float, 0x2dc),
            Field("epic_SuffixDist", DataType.Float, 0x320),
            Field("epic_Prefix1Dist", DataType.Float, 0x324),
            Field("epic_Prefix2Dist", DataType.Float, 0x328),
            Field("epic_StandardDist", DataType.Float, 0x32c),
            Field("itemCost_Multiplier", DataType.Float, 0x330),
            Field("itemCost_LevelPower", DataType.Float, 0x334),
            Field("itemCost_RoundingVal", DataType.Int, 0x338),
            Field("baseStatScale_Other", DataType.Float, 0x33c),
            Field("baseStatScale_Hand", DataType.Float, 0x340),
            Field("baseStatScale_HandTwo", DataType.Float, 0x344),
            Field("baseStatScale_Feet", DataType.Float, 0x348),
            Field("baseStatScale_FeetTwo", DataType.Float, 0x34c),
            Field("baseStatScale_Offense", DataType.Float, 0x350),
            Field("baseStatScale_Defense", DataType.Float, 0x354),
            Field("baseStatScale_Utility", DataType.Float, 0x358),
            Field("minDropLevel_Hands", DataType.Int, 0x35c),
            Field("minDropLevel_Feet", DataType.Int, 0x360),
            Field("minDropLevel_Weapons", DataType.Int, 0x364),
            Field("minDropLevel_Offense", DataType.Int, 0x368),
            Field("minDropLevel_Defense", DataType.Int, 0x36c),
            Field("minDropLevel_Utility", DataType.Int, 0x370),
            Field("weaponDamage_Scaler", DataType.Float, 0x374)
        );
    }
}