namespace ReCap.Parser.Catalog;

public sealed class LootPrefix : AssetCatalog
{
    protected override void Build()
    {
        Struct("LootPrefix", 0x234,
            Field("objective", DataType.UInt32, 0x0),
            ArrayStruct("partTypes", "LootData", 0x4),
            ArrayStruct("classTypes", "LootData", 0xc),
            ArrayStruct("scienceTypes", "LootData", 0x14),
            ArrayStruct("modifierGranted", "LootData", 0x1f4),
            ArrayStruct("abilityImproved", "LootData", 0x1fc),
            Field("minLevel", DataType.Int, 0x1c),
            Field("maxLevel", DataType.Int, 0x20),
            Field("strength", DataType.Float, 0x24),
            Field("dexterity", DataType.Float, 0x28),
            Field("mind", DataType.Float, 0x2c),
            Field("health", DataType.Float, 0x34),
            Field("mana", DataType.Float, 0x38),
            Field("critical", DataType.Float, 0x4c),
            Field("criticalDamage", DataType.Float, 0x7c),
            Field("physicalDefense", DataType.Float, 0x40),
            Field("energyDefense", DataType.Float, 0x48),
            Field("projectileSpeed", DataType.Float, 0x8c),
            Field("cooldown", DataType.Float, 0x84),
            Field("aoeDamage", DataType.Float, 0xb8),
            Field("aoeResistance", DataType.Float, 0x90),
            Field("movementSpeed", DataType.Float, 0xe4),
            Field("lifeSteal", DataType.Float, 0xb0),
            Field("manaSteal", DataType.Float, 0xf4),
            Field("attackSpeed", DataType.Float, 0x80),
            Field("damageLifeType", DataType.Float, 0xc4),
            Field("damageTechType", DataType.Float, 0xbc),
            Field("damageQuantumType", DataType.Float, 0xc0),
            Field("damageNecroType", DataType.Float, 0xcc),
            Field("damagePlasmaType", DataType.Float, 0xc8),
            Field("resistLifeType", DataType.Float, 0xd8),
            Field("resistTechType", DataType.Float, 0xd0),
            Field("resistQuantumType", DataType.Float, 0xd4),
            Field("resistNecroType", DataType.Float, 0xe0),
            Field("resistPlasmaType", DataType.Float, 0xdc),
            Field("aoeRadius", DataType.Float, 0x11c),
            Field("petDamage", DataType.Float, 0x120),
            Field("petHealth", DataType.Float, 0x124),
            Field("crystalFind%", DataType.Float, 0x128),
            Field("lootFind%", DataType.Float, 0x140),
            Field("dnaDropped%", DataType.Float, 0x12c),
            Field("rangeIncrease", DataType.Float, 0x130),
            Field("orbEffect", DataType.Float, 0x134),
            Field("overdriveBuildup%", DataType.Float, 0x138),
            Field("overdriveDuration%", DataType.Float, 0x13c),
            Field("surefooted%", DataType.Float, 0x144),
            Field("buffDuration%", DataType.Float, 0xec),
            Field("debuffShorten%", DataType.Float, 0xf0),
            Field("debuffLengthen%", DataType.Float, 0xf8),
            Field("dotDamage%%", DataType.Float, 0x178),
            Field("aggroInc%", DataType.Float, 0x17c),
            Field("aggroDec%", DataType.Float, 0x180),
            Field("physDmg%", DataType.Float, 0x184),
            Field("physAbDmg%", DataType.Float, 0x188),
            Field("energyDmg%", DataType.Float, 0x18c),
            Field("energyAbDmg%", DataType.Float, 0x190),
            Field("immStun", DataType.Float, 0x148),
            Field("immBanish", DataType.Float, 0x114),
            Field("immKnockBack", DataType.Float, 0x118),
            Field("immSleep", DataType.Float, 0x150),
            Field("immTaunt", DataType.Float, 0x154),
            Field("immTerror", DataType.Float, 0x158),
            Field("immSilence", DataType.Float, 0x15c),
            Field("immCurse", DataType.Float, 0x160),
            Field("immPoison", DataType.Float, 0x164),
            Field("immBurn", DataType.Float, 0x168),
            Field("immRoot", DataType.Float, 0x16c),
            Field("immSlow", DataType.Float, 0x170),
            Field("immPull", DataType.Float, 0x174),
            Field("channelTime%", DataType.Float, 0x194),
            Field("ccDur%", DataType.Float, 0x198),
            Field("dotDur%", DataType.Float, 0x19c),
            Field("aoeDurInc%", DataType.Float, 0x1a0),
            Field("healInc%", DataType.Float, 0x1a4),
            Field("deploy", DataType.Float, 0x1b8),
            Field("physDmgDecFlat", DataType.Float, 0x1bc),
            Field("energyDmgDecFlat", DataType.Float, 0x1c0),
            Field("minWpnDmg", DataType.Float, 0x1c4),
            Field("maxWpnDmg", DataType.Float, 0x1c8),
            Field("minWpnDmg%", DataType.Float, 0x1cc),
            Field("maxWpnDmg%", DataType.Float, 0x1d0),
            Field("attDmg", DataType.Float, 0x1d4),
            Field("attDmg%", DataType.Float, 0x1d8),
            Field("xpBoost%", DataType.Float, 0x1e0)
        );
    }
}
