namespace ReCap.Parser.Catalog;

public sealed class LootSuffix : AssetCatalog
{
    protected override void Build()
    {
        Struct("LootSuffix", 0x248,
            Field("suffixId", DataType.UInt32, 0x0),
            Field("suffixName", DataType.Key, 0x10),
            Field("minLevel", DataType.Int, 0x14),
            Field("maxLevel", DataType.Int, 0x18),
            ArrayStruct("partTypes", "LootData", 0x1c),
            ArrayStruct("classTypes", "LootData", 0x24),
            ArrayStruct("scienceTypes", "LootData", 0x2c),
            Field("isUnique", DataType.Bool, 0x34),
            Field("isBasic", DataType.Bool, 0x35),
            ArrayStruct("modifierGranted", "LootData", 0x208),
            ArrayStruct("abilityImproved", "LootData", 0x210),
            Field("strength", DataType.Float, 0x38),
            Field("dexterity", DataType.Float, 0x3c),
            Field("mind", DataType.Float, 0x40),
            Field("health", DataType.Float, 0x48),
            Field("mana", DataType.Float, 0x4c),
            Field("critical", DataType.Float, 0x60),
            Field("criticalDamage", DataType.Float, 0x90),
            Field("physicalDefense", DataType.Float, 0x54),
            Field("energyDefense", DataType.Float, 0x5c),
            Field("projectileSpeed", DataType.Float, 0xa0),
            Field("cooldown", DataType.Float, 0x98),
            Field("aoeDamage", DataType.Float, 0xcc),
            Field("aoeResistance", DataType.Float, 0xa4),
            Field("movementSpeed", DataType.Float, 0xf8),
            Field("lifeSteal", DataType.Float, 0xc4),
            Field("manaSteal", DataType.Float, 0x108),
            Field("attackSpeed", DataType.Float, 0x94),
            Field("damageLifeType", DataType.Float, 0xd8),
            Field("damageTechType", DataType.Float, 0xd0),
            Field("damageQuantumType", DataType.Float, 0xd4),
            Field("damageNecroType", DataType.Float, 0xe0),
            Field("damagePlasmaType", DataType.Float, 0xdc),
            Field("resistLifeType", DataType.Float, 0xec),
            Field("resistTechType", DataType.Float, 0xe4),
            Field("resistQuantumType", DataType.Float, 0xe8),
            Field("resistNecroType", DataType.Float, 0xf4),
            Field("resistPlasmaType", DataType.Float, 0xf0),
            Field("aoeRadius", DataType.Float, 0x130),
            Field("petDamage", DataType.Float, 0x134),
            Field("petHealth", DataType.Float, 0x138),
            Field("crystalFind%", DataType.Float, 0x13c),
            Field("lootFind%", DataType.Float, 0x154),
            Field("dnaDropped%", DataType.Float, 0x140),
            Field("rangeIncrease", DataType.Float, 0x144),
            Field("orbEffect", DataType.Float, 0x148),
            Field("overdriveBuildup%", DataType.Float, 0x14c),
            Field("overdriveDuration%", DataType.Float, 0x150),
            Field("surefooted%", DataType.Float, 0x158),
            Field("buffDuration%", DataType.Float, 0x100),
            Field("debuffShorten%", DataType.Float, 0x104),
            Field("debuffLengthen%", DataType.Float, 0x10c),
            Field("dotDamage%", DataType.Float, 0x18c),
            Field("aggroInc%", DataType.Float, 0x190),
            Field("aggroDec%", DataType.Float, 0x194),
            Field("physDmg%", DataType.Float, 0x198),
            Field("physAbDmg%", DataType.Float, 0x19c),
            Field("energyDmg%", DataType.Float, 0x1a0),
            Field("energyAbDmg%", DataType.Float, 0x1a4),
            Field("immStun", DataType.Float, 0x15c),
            Field("immBanish", DataType.Float, 0x128),
            Field("immKnockBack", DataType.Float, 0x12c),
            Field("immSleep", DataType.Float, 0x164),
            Field("immTaunt", DataType.Float, 0x168),
            Field("immTerror", DataType.Float, 0x16c),
            Field("immSilence", DataType.Float, 0x170),
            Field("immCurse", DataType.Float, 0x174),
            Field("immPoison", DataType.Float, 0x178),
            Field("immBurn", DataType.Float, 0x17c),
            Field("immRoot", DataType.Float, 0x180),
            Field("immSlow", DataType.Float, 0x184),
            Field("immPull", DataType.Float, 0x188),
            Field("channelTime%", DataType.Float, 0x1a8),
            Field("ccDur%", DataType.Float, 0x1ac),
            Field("dotDur%", DataType.Float, 0x1b0),
            Field("aoeDurInc%", DataType.Float, 0x1b4),
            Field("healInc%", DataType.Float, 0x1b8),
            Field("deploy", DataType.Float, 0x1cc),
            Field("physDmgDecFlat", DataType.Float, 0x1d0),
            Field("energyDmgDecFlat", DataType.Float, 0x1d4),
            Field("minWpnDmg", DataType.Float, 0x1d8),
            Field("maxWpnDmg", DataType.Float, 0x1dc),
            Field("minWpnDmg%", DataType.Float, 0x1e0),
            Field("maxWpnDmg%", DataType.Float, 0x1e4),
            Field("attDmg", DataType.Float, 0x1e8),
            Field("attDmg%", DataType.Float, 0x1ec),
            Field("xpBoost%", DataType.Float, 0x1f4)
        );
    }
}
