namespace ReCap.Parser.Catalog;

public sealed class SpaceshipTuning : AssetCatalog
{
    protected override void Build()
    {
        Struct("SpaceshipTuning", 0x29c,
            Field("level", DataType.Asset, 0x0),
            Field("conga_line_move_speed", DataType.Float, 0x4),
            Field("dias_offset", DataType.Vector3, 0x8),
            Field("ui_delay_after_animation", DataType.Float, 0x14),
            Field("ui_delay_mouseover", DataType.Float, 0x18),
            Field("dias_light_default_color", DataType.Vector3, 0x1c),
            Field("dias_light_swap_color", DataType.Vector3, 0x28),
            Field("dias_light_locked_color", DataType.Vector3, 0x34),
            Field("dias_light_collectable_color", DataType.Vector3, 0x40),
            Field("dias_light_in_deck_color", DataType.Vector3, 0x4c),
            ArrayStruct("camera_start_collection", "cSpaceshipCameraTuning", 0x58),
            ArrayStruct("camera_start_map", "cSpaceshipCameraTuning", 0x60),
            ArrayStruct("camera_start_planet", "cSpaceshipCameraTuning", 0x68),
            ArrayStruct("camera_collection_map", "cSpaceshipCameraTuning", 0x70),
            ArrayStruct("camera_collection_editor", "cSpaceshipCameraTuning", 0x78),
            ArrayStruct("camera_map_collection", "cSpaceshipCameraTuning", 0x80),
            ArrayStruct("camera_map_editor", "cSpaceshipCameraTuning", 0x88),
            ArrayStruct("camera_editor_collection", "cSpaceshipCameraTuning", 0x90),
            ArrayStruct("camera_editor_map", "cSpaceshipCameraTuning", 0x98),
            ArrayStruct("camera_map_planet", "cSpaceshipCameraTuning", 0xa0),
            ArrayStruct("camera_planet_game", "cSpaceshipCameraTuning", 0xa8),
            ArrayStruct("camera_planet_collection", "cSpaceshipCameraTuning", 0xb0),
            ArrayStruct("camera_planet_editor", "cSpaceshipCameraTuning", 0xb8),
            Field("small_placard_offset_base", DataType.Vector3, 0xc0),
            Field("small_placard_rotation_base", DataType.Vector3, 0xcc),
            Field("small_placard_scale_base", DataType.Float, 0xd8),
            Array("small_placard_offset", DataType.Vector3, 0xdc),
            Array("small_placard_rotation", DataType.Vector3, 0xe4),
            Array("small_placard_scale", DataType.Float, 0xec),
            Field("small_deck_placard_offset_base", DataType.Vector3, 0xf4),
            Field("small_deck_placard_rotation_base", DataType.Vector3, 0x100),
            Field("small_deck_placard_scale_base", DataType.Float, 0x10c),
            Array("small_deck_placard_offset", DataType.Vector3, 0xc),
            Array("small_deck_placard_rotation", DataType.Vector3, 0x118),
            Array("small_deck_placard_scale", DataType.Float, 0x120),
            Field("large_placard_offset_base", DataType.Vector3, 0x128),
            Field("large_placard_rotation_base", DataType.Vector3, 0x134),
            Field("large_placard_scale_base", DataType.Float, 0x140),
            Array("large_placard_offset", DataType.Vector3, 0x144),
            Array("large_placard_rotation", DataType.Vector3, 0x14c),
            Array("large_placard_scale", DataType.Float, 0x154),
            Field("large_deck_placard_offset_base", DataType.Vector3, 0x15c),
            Field("large_deck_placard_rotation_base", DataType.Vector3, 0x168),
            Field("large_deck_placard_scale_base", DataType.Float, 0x174),
            Array("large_deck_placard_offset", DataType.Vector3, 0x178),
            Array("large_deck_placard_rotation", DataType.Vector3, 0x180),
            Array("large_deck_placard_scale", DataType.Float, 0x188),
            Field("context_menu_offset_base", DataType.Vector3, 0x190),
            Field("context_menu_rotation_base", DataType.Vector3, 0x19c),
            Field("context_menu_scale_base", DataType.Float, 0x1a8),
            Field("context_menu_offset", DataType.Float, 0x1ac),
            Array("context_menu_rotation", DataType.Vector3, 0x1b4),
            Array("context_menu_scale", DataType.Float, 0x1bc),
            Field("deck_context_menu_offset_base", DataType.Vector3, 0x1c4),
            Field("deck_context_menu_rotation_base", DataType.Vector3, 0x1d0),
            Field("deck_context_menu_scale_base", DataType.Float, 0x1dc),
            Array("deck_context_menu_offset", DataType.Vector3, 0x1e0),
            Array("deck_context_menu_rotation", DataType.Vector3, 0x1e8),
            Array("deck_context_menu_scale", DataType.Float, 0x1f0),
            Field("empty_squad_slot_offset_base", DataType.Vector3, 0x1f8),
            Field("empty_squad_slot_rotation_base", DataType.Vector3, 0x204),
            Field("empty_squad_slot_scale_base", DataType.Float, 0x210),
            Array("empty_squad_slot_offset", DataType.Vector3, 0x214),
            Array("empty_squad_slot_rotation", DataType.Vector3, 0x21c),
            Array("empty_squad_slot_scale", DataType.Float, 0x224),
            Field("controls_offset", DataType.Vector3, 0x22c),
            Field("controls_rotation", DataType.Vector3, 0x238),
            Field("controls_scale", DataType.Float, 0x244),
            Field("squad_controls_offset", DataType.Vector3, 0x248),
            Field("squad_controls_rotation", DataType.Vector3, 0x254),
            Field("squad_controls_scale", DataType.Float, 0x260),
            Field("map_room_ui_offset", DataType.Vector3, 0x264),
            Field("map_room_ui_rotation", DataType.Vector3, 0x270),
            Field("map_room_ui_scale", DataType.Float, 0x27c),
            Field("planet_screen_ui_offset", DataType.Vector3, 0x280),
            Field("planet_screen_ui_rotation", DataType.Vector3, 0x28c),
            Field("planet_screen_ui_scale", DataType.Float, 0x298)
        );
    }
}
